""" 

This script runs the likelihood calculation for MC truth parameters,
(which are reproduced from emcee fitting), and analyses the posterior
distribution of observables in host magnitude and angular offset.

It requires one to have first run "run_path_only.py", since it 
makes comparison plots of posterior observables to those derived
when running PATH without zDM priors.
"""
import os
import time
import pandas as pd

from zdm import iteration as it
from zdm import loading
from zdm import optical as opt
from zdm import optical_params as op
from zdm import states
from zdm import misc_functions as mf

import numpy as np

from matplotlib import pyplot as plt
import importlib.resources as resources

import matplotlib
defaultsize=14
ds=4
font = {'family' : 'Helvetica',
        'weight' : 'normal',
        'size'   : defaultsize}
matplotlib.rc('font', **font)


def main(prefix,pathfile,wpathfile,hostfile,zdmfile,CandDir,image_size,PlotCorrected=False):
    """
    Calculates likelihoods for fake survey
    
        
        prefix (string): prefix to label outputs
        
        pathfile (string): name of file containing PATH-only outputs generated by run_path_only.py,
                    when constraining to P(O|x)>0.95
        
        wpathfile (string): name of file containing PATH-only outputs generated by run_path_only.py
                    when weighting by all P(O|x)
                    
        hostfile (string): name of file containing assigned hosts, generated by run_assign_host.py   
        
        zdmfile (string): name of file containing MC generated FRBs, generated by gen_mc_frbs_w_hosts.py 
        
        CandDir (string): name of directory containing candidate files
        
        Image_size (float): is size of image in arcsec**2
    """
    opdir = "LikelihoodTests/"
    if not os.path.exists(opdir):
        os.mkdir(opdir)
    
    opdir = opdir+prefix
    
    state = states.load_state("HoffmannHalo25") # old scattering
    state.MW.sigmaHalo=0.
    state.MW.sigmaDM=0.
    state.energy.lEmin = 30.
    
    # survey file remains the same, regardless of the localisation
    name = "short_fake_CRACO_900" # do this with very short
    #name = "1M_fake_CRACO"
    sdir = resources.files('zdm').joinpath('../papers/CombinedPathzDM/BridgetMC/Surveys/')
    surveys, grids = loading.surveys_and_grids(survey_names = [name],repeaters=False,
                                                sdir=sdir,init_state=state)
    
    
    s = surveys[0]
    g = grids[0]
    
    ####### check plot for z distribution #######
    plot_z_check(g,zdmfile,opdir)
    
    
    ###### load optical model #####
    opstate = op.OpticalState()
    opstate.loudas.fSFR=1.5
    opstate.id.pU_method=1
    opstate.id.pU_min=14
    opstate.id.pU_max=22
    model = opt.loudas_model(opstate)
    wrapper = opt.model_wrapper(model,g.zvals)
    
    ### sets system variables to point towards fake FRB data
    relgaldir="../papers/CombinedPathzDM/BridgetMC/"+prefix+"CandidateFiles"
    galdir = resources.files('zdm').joinpath(relgaldir)
    relfrbdir = "../papers/CombinedPathzDM/BridgetMC/"+prefix+"FRBFiles"
    frbdir = resources.files('zdm').joinpath(relfrbdir)
    os.environ["ZDM_PATH_FRBDIR"] = str(frbdir)
    os.environ["ZDM_PATH_GALDIR"] = str(galdir)
    
    # adds this flag. Actual value doesn't matter, provided it is set
    os.environ["ZDM_CORRECT_DRIVER_FLAG"] = "False"
    
    lltot,results = it.get_joint_path_zdm_likelihoods(g, s, wrapper, norm=True, psnr=True, Pn=False,
                                    pdmz=True, pNreps=True, ptauw=False, pwb=True,
                                    return_all=True)
    
    # adds this flag. Actual value doesn't matter, provided it is set
    os.environ["ZDM_CORRECT_DRIVER_FLAG"] = "True"
                         
    lltot2,results2 = it.get_joint_path_zdm_likelihoods(g, s, wrapper, norm=True, psnr=True, Pn=False,
                                    pdmz=True, pNreps=True, ptauw=False, pwb=True,
                                    return_all=True)
    
    
    # we now construct posterior distributions
    # loop over FRBs. CHECK: if this total number of FRBs, or total with PATH results?
    weights = []
    otherweights = [] # an alternative weighting, for debugging purposes. This weight is just the prior on magnitude
    thetas = []
    truths = []
    thetas2 = []
    mags = []
    path_results = results['path_s']
    # keys to path results are:
    # dict_keys(['NFRB', 'ObsMags', 'PO', 'POx', 'PxO', 'PU', 'PUx', 'sumPU',
    #        'sumPUx', 'OK', 'frblist', 'seps', 'sizes', 'Ncand', 'pz', 'pf',
    #        'AppMags', 'AppMagPriors', 'dms', 'rhom', 'Pm', 'llpath'])
    # I should be able to reconstruct galaxies according to their priors, i.e.
    
    
    zdm_results = results['zdm_s']
    csum_pux = path_results["sumPUx"]
    
    # results when using the correction function
    cpath_results = results2['path_s']
    czdm_results = results2['zdm_s']
    cweights = []
    cthetas = []
    ctruths = []
    cthetas2 = []
    cmags = []
    csum_pux = cpath_results["sumPUx"]
    
    HostCount=0
    
    # print out the keys so we know what's available!
    for i in np.arange(path_results["NFRB"]):
        
        # gets correct candidate
        Candfile=CandDir+"FRB"+str(i)+"_PATH.csv"
        cands = pd.read_csv(Candfile)
        ihost = np.where(cands["z"] > 0.)[0] # this is the correct one - "known" z
        if len(ihost) == 1:
            maghost = cands["mag"][ihost[0]]
            HostCount += 1
        else:
            maghost = -1e9
        
        for j in np.arange(path_results["Ncand"][i]):
            weights = weights+[path_results["POx"][i][j]]
            otherweights = otherweights+[path_results["PxO"][i][j]]
            mag = path_results["ObsMags"][i][j]
            if np.abs(mag - maghost) < 1e-10:
                true = 1
            else:
                true = 0
            truths = truths + [true]
            mags = mags+[mag]
            thetas = thetas+[path_results["seps"][i][j]/path_results["sizes"][i][j]]
            effr = (path_results["sizes"][i][j]**2 + 0.5**2)**0.5
            thetas2 = thetas2+[path_results["seps"][i][j]/effr]
            
        
        # should actually be the same loop as above, since candidates are fixed
        for j in np.arange(cpath_results["Ncand"][i]):
            cweights = cweights+[cpath_results["POx"][i][j]]
            cmag = cpath_results["ObsMags"][i][j]
            if np.abs(cmag - maghost) < 1e-10:
                true = 1
            else:
                true = 0
            ctruths = ctruths + [true]
            cmags = cmags+[cmag]
            cthetas = cthetas+[cpath_results["seps"][i][j]/cpath_results["sizes"][i][j]]
            ceffr = (cpath_results["sizes"][i][j]**2 + 0.5**2)**0.5
            cthetas2 = cthetas2+[cpath_results["seps"][i][j]/ceffr]
    
    print("We have ",HostCount," true hosts, of ",path_results["NFRB"]," FRBs total")
    print("We expected to miss ",path_results["sumPU"]," FRBs - it was actually ",path_results["NFRB"]-HostCount)
    
    pms,mvals = get_expected_mags(wrapper,g,len(mags))
    
    mags = np.array(mags)
    weights = np.array(weights)
    truths = np.array(truths)
    otherweights = np.array(otherweights)
    
    cmags = np.array(cmags)
    cweights = np.array(cweights)
    ctruths = np.array(truths)
    
    
    # ensure correct weighting
    NGal = len(mags)
    weights *= NGal/np.sum(weights)
    
    # adds in simple PATH cuts
    path = pd.read_csv(pathfile)
    if len(path) > 0:
        dopath = True
    else:
        dopath=False
    
    if dopath:
        pweights = np.full([len(path)],NGal / len(path))
    
    
    # generates magnitude distribution comparison plot
    compare_mag_dists(wrapper,zdmfile,hostfile,opdir)
    
    
    # gets true assigned host distribution
    assigned = pd.read_csv(hostfile)
    truemags = assigned["mag"].values
    truemags = np.sort(truemags)
    NT = truemags.size
    OK = np.where(truemags >= 14.)
    truemags = truemags[OK]
    OK = np.where(truemags <= 22.)
    truemags = truemags[OK]
    NT = truemags.size
    ctruemags = np.linspace(1./NT,1.,NT)
    
    wpath = pd.read_csv(wpathfile)
    wpweights = wpath["POx"] * NGal / np.sum(wpath["POx"])
    
    trueweights = np.full([NT],NGal/NT)
    
    
    # make pots of true and false host contributions
    make_true_false_distributions(weights,otherweights,mags,truths,opdir,truemags,image_size)
    if PlotCorrected:
        make_true_false_distributions(cweights,otherweights,cmags,ctruths,opdir+"corrected_",truemags,image_size)
    

    ####### Histogram of host magnitudes #########
    
    plt.figure()
    bins = wrapper.AppBins
    plt.hist(mags,bins=bins,label="All host candidates")
    plt.hist(mags,weights=weights,bins=bins,label="Posterior weights",alpha=0.7)
    if dopath:
        plt.hist(path["mags"],weights=pweights,bins=bins,label="Standard PATH",alpha=0.5)
        #plt.text('a): $\\sigma_{\\rm frb} = 0.5^{"}$')
    #   else:
        #plt.text('b): $\\sigma_{\\rm frb} = 30^{"}$')
    plt.hist(wpath["mags"],weights=wpweights,bins=bins,label="weighted PATH",alpha=0.3)
    plt.plot(wrapper.AppMags,pms,label="Truth")
    plt.hist(truemags,bins=bins,weights=trueweights,label="Assigned")
    
    plt.xlim(13,23)
    plt.xlabel("$m_r$")
    plt.ylabel("$N(m_r)$")
    plt.legend(loc="upper left")
    plt.tight_layout()
    plt.savefig(opdir+"post_mags.png")
    plt.close()
    
    ##### Cumulative distribution of host magnitudes ######
    
    # performs a CDF plot of each
    iorder = np.argsort(mags)
    x = mags[iorder]
    weights = weights[iorder]
    # unweighted
    raw_cdf = np.linspace(1./mags.size,1.,mags.size)
    # posterior
    post_cdf = np.cumsum(weights)
    post_cdf /= post_cdf[-1]
    
    
    # Corrected post CDF
    iorder = np.argsort(cmags)
    cx = cmags[iorder]
    cweights = cweights[iorder]
    # unweighted
    craw_cdf = np.linspace(1./mags.size,1.,mags.size)
    # posterior
    cpost_cdf = np.cumsum(cweights)
    cpost_cdf /= cpost_cdf[-1]
    
    # traditional_path
    if dopath:
        xpath = np.sort(path["mags"])
        print("N path is : ",len(xpath))
        trad_cdf = np.linspace(1./xpath.size,1.,xpath.size)
    
    # weighted_path
    wxmags = wpath["mags"].values
    iwxpath = np.argsort(wxmags)
    wxpath = wxmags[iwxpath]
    wp_cdf = wpath["POx"].values
    wp_cdf = wp_cdf[iwxpath]
    wp_cdf = np.cumsum(wp_cdf)
    wp_cdf /= wp_cdf[-1]
    
    mvals = wrapper.AppMags
    # truth. We restrict our range to the 14-22 magnitude range covered by the simulation
    OK = np.where(mvals > 14)[0]
    mvals = mvals[OK]
    pms = pms[OK]
    OK = np.where(mvals < 22)[0]
    mvals = mvals[OK]
    pms = pms[OK]
    pms = np.cumsum(pms)
    pms /= pms[-1]
    
    # plot
    plt.figure()
    plt.plot(mvals,pms,label="Simulated truth",color="black",linestyle=":")
    plt.plot(truemags,ctruemags,label="Assigned hosts",color="black",linestyle="-")
    
    plt.plot(x,raw_cdf,label="All candidates",linestyle=":")
    plt.plot(cx,cpost_cdf,label="zDM+PATH (this work)",linestyle="-")
    if PlotCorrected:
        plt.plot(x,post_cdf,label="  (uncorrected $\\rho_{D16}$)",linestyle=":",color=plt.gca().lines[-1].get_color())
    
    if dopath:
        plt.plot(xpath,trad_cdf,label="PATH: $P(O|x)>0.95$",linestyle="--")
        plt.text(13,1.05,"a): $\\sigma_{\\rm FRB} = 0.5^{''}$")
    else:
        plt.text(13,1.05,"b): $\\sigma_{\\rm FRB} = 30^{''}$")
    plt.plot(wxpath,wp_cdf,label="PATH: $\\propto P(O|x)$",linestyle="-.",color="red")
    
    plt.xlabel("$m_r$")
    plt.ylabel("CDF$(m_r)$")
    plt.legend(fontsize=12)
    plt.xlim(14,22)
    plt.ylim(0,1)
    plt.tight_layout()
    plt.savefig(opdir+"mag_dist_cumulative.png")
    plt.close()
    
    ####### Histogram of host offsets ###########
    
    plt.figure()
    bins = np.linspace(0,6.,61)
    
    # note: "truth" does *NOT* account for angular smearing of FRB localisation
    # However, PATH does! So we don't expect agreement
    truth = bins*np.exp(-bins/0.5) * np.sum(weights)/10
    truth *= NGal / np.sum(truth)
    plt.hist(thetas,bins=bins,label="All host candidates")
    plt.hist(thetas,bins=bins,weights=weights,label="zDM+PATH: weighted",alpha=0.5)
    #plt.hist(thetas2,bins=bins,weights=weights,label="Adjusted posterior weights",alpha=0.3)
    plt.plot(bins,truth,label="Simulated truth",color="black")
    plt.legend()
    plt.xlim(0,6)
    plt.xlabel("$\\theta/\\phi$")
    plt.ylabel("$N(\\theta/\\phi)$")
    plt.tight_layout()
    plt.savefig(opdir+"post_offsets.png")
    plt.close()
    

def make_true_false_distributions(weights,otherweights,mags,truths,opdir,truemags,image_size):
    """
    Makes a scatter plot of posterior P(O|xrad,xopt) for both real and incorrect hosts
    
    """
    
    
    ####### make a scatter plots of final weights, separated into true and false hosts ########
    TRUE = np.where(truths==1)[0]
    FALSE = np.where(truths == 0)[0]
    plt.figure()
    plt.scatter(mags[TRUE],weights[TRUE],label="True hosts")
    plt.scatter(mags[FALSE],weights[FALSE],label="Field galaxies")
    plt.xlabel("$m_r$")
    plt.ylabel("$P(O|\\mathbf{x}_{\\rm rad},\\mathbf{x}_{\\rm opt})$")
    plt.ylim(0,1)
    
    plt.xlim(14,22)
    plt.legend()
    plt.tight_layout()
    plt.savefig(opdir+"scatter_weights.png")
    plt.yscale("log")
    plt.ylim(1e-4,1.01)
    plt.tight_layout()
    plt.savefig(opdir+"scatter_weights_log.png")
    plt.close()
    
    ####### make a scatter plots of PxO, separated into true and false hosts ########
    # we expect P(x|O) to be about 100% for true hosts, given that uncertainty is terrible.
    # it should generally be less for field galaxies
    plt.figure()
    plt.scatter(mags[TRUE],otherweights[TRUE],label="True hosts")
    plt.scatter(mags[FALSE],otherweights[FALSE],label="Field galaxies")
    plt.xlabel("$m_r$")
    plt.ylabel("$P(x|O)$")
    #plt.ylim(0,1)
    
    plt.xlim(14,22)
    plt.legend()
    plt.tight_layout()
    plt.savefig(opdir+"scatter_otherweights.png")
    plt.yscale("log")
    #plt.ylim(1e-4,1.01)
    plt.tight_layout()
    plt.savefig(opdir+"scatter_otherweights_log.png")
    plt.close()
    
    #### makes a histogram of these values ######
    
    plt.figure()
    bins = np.logspace(-10,0,21)
    plt.hist(otherweights[TRUE],bins=bins,label="True Hosts",histtype='step')
    plt.hist(otherweights[FALSE],bins=bins,label="False Hosts",histtype='step')
    plt.xlabel("$P(x|O)$")
    plt.ylabel("N[$P(x|O)]$")
    plt.xscale("log")
    plt.legend()
    plt.tight_layout()
    plt.savefig(opdir+"hist_otherweights_log.png")
    plt.close()
    
    # calculate number density per arcsec^2
    from astropath import chance
    Nfbins=100
    # range of 14 to 22 is hard-coded, for good reason
    fieldmags = np.linspace(14 + 4./Nfbins,22.0-4./Nfbins,Nfbins)
    expected = chance.differential_driver_sigma(fieldmags) * (8./Nfbins) # bin size - reduce to number per bin, in mags
    NFRB = truemags.size
    expected *= NFRB * image_size
    cexpected = np.cumsum(expected)
    Nfield = len(FALSE)
    print("We expect a total of ",cexpected[-1]," field galaxies. Actually saw ",Nfield)
    cexpected /= cexpected[-1]
    
    # makes an unweighted field galaxy population, compared to expectation
    xfield_gs = np.sort(mags[FALSE])
    yfield_gs = np.linspace(1./xfield_gs.size,1.,xfield_gs.size)
    
    mtrue = mags[TRUE]
    order = np.argsort(mtrue) # sorted mags
    mtrue = mtrue[order]
    wtrue = weights[TRUE][order]
    cwtrue = np.cumsum(wtrue)
    
    mfalse = mags[FALSE]
    order = np.argsort(mfalse) # sorted mags
    mfalse = mfalse[order]
    wfalse = weights[FALSE][order]
    cwfalse = np.cumsum(wfalse)
    
    # true assigned magnitudes
    xtmags = np.sort(truemags)
    ytmags = np.linspace(1./xtmags.size,1.,xtmags.size)
    
    norm = cwtrue[-1] + cwfalse[-1]
    
    cwtrue /= norm
    cwfalse /= norm
    
    plt.figure()
    plt.plot(mtrue,cwtrue,label="Weighted true hosts")
    plt.plot(mfalse,cwfalse,label="Weighted field galaxies")
    plt.plot(xtmags,ytmags,label="Unweighted hosts")
    plt.plot(xfield_gs,yfield_gs,label="Unweighted field galaxies")
    
    plt.plot(fieldmags,cexpected,label="Expected field galaxies")
    
    plt.xlabel("$m_r$")
    plt.ylabel("$P(m_r)$")
    plt.ylim(0,1)
    plt.legend()
    plt.tight_layout()
    plt.savefig(opdir+"cumulative_contributions.png")
    plt.close()
    
    

def get_expected_mags(wrapper,g,NGal):
    """
    gets expected magnitude distributon, according to model
    """
    # we now construct the expectation
    # does this for each point on the zdm grid
    mvals = wrapper.AppMags
    pms = np.zeros([mvals.size])
    for i,z in enumerate(g.zvals):
        weight = np.sum(g.rates[i,:])
        pmag = wrapper.get_pm_g_z(z)
        pms[:] += pmag * weight
    
    pms *= NGal/np.sum(pms)
    return pms,mvals

def plot_z_check(g,zdmfile,opdir):
    """
    Generates a plot of generated compared to expected zvalues
    """
    # we quickly check that the generated FRBs follow the correct distribution anticipated by the model
    rates = g.get_rates()
    pz = np.sum(rates,axis=1)
    
    cpz= np.cumsum(pz)
    cpz /= cpz[-1]
    
    zdm = pd.read_csv(zdmfile)
    zvals = zdm["z"]
    zvals = np.sort(zvals)
    zx,zy = mf.make_cum_dist(zvals)
    plt.figure()
    plt.plot(g.zvals,cpz,label="expectation")
    plt.plot(zx,zy,label="generated")
    plt.xlabel("z")
    plt.ylabel("cdf(z)")
    plt.legend()
    plt.tight_layout()
    plt.xlim(0,2)
    plt.savefig(opdir+"cdf_z_comparison.png")
    plt.close()

def compare_mag_dists(wrapper,zdmfile,hostfile,opdir):
    """
    Generates a cmulative distribution plot comparing
    expected, generated, and assigned FRB host magnitudes
    """
    
    ######## checks that the magnitude distributions match #####
    
    zdm = pd.read_csv(zdmfile)
    zvals = zdm["z"]
    allpmdist=0.
    # for every actual FRB, generate a p(dm|z) distribution
    for i,z in enumerate(zvals):
        pmdist = wrapper.get_pm_g_z(z)
        allpmdist += pmdist
    appmags = wrapper.AppMags
    
    callpmdist = np.cumsum(allpmdist)
    callpmdist = callpmdist / callpmdist[-1]
    
    wrapper.gen_mc_mr(np.array([0.1]))
    
    # actual dist
    hosts = pd.read_csv(hostfile)
    mags = hosts["mag"]
    mx,my = mf.make_cum_dist(mags)
    
    mags2 = zdm["m_r"]
    mx2,my2 = mf.make_cum_dist(mags2)
    
    plt.figure()
    plt.plot(appmags,callpmdist,label="Predicted")
    plt.plot(mx2,my2,label="Generated")
    plt.plot(mx,my,label="Assigned")
    plt.xlabel("m")
    plt.ylabel("cdf(m)")
    plt.legend()
    plt.tight_layout()
    plt.savefig(opdir+"magnitude_comparison.png")
    plt.close()

def get_convolution():
    """
    convolves gaussian with exponential
    """
    N=7
    xvals = np.linspace(-6,6,N)
    xvals = np.repeat(xvals,N)
    xvals = xvals.reshape([N,N])
    print(xvals)
    
    yvals = xvals.T
    print(yvals)
    
    rs = (xvals**2 + yvals**2)**0.5
    p1 = np.exp(xvals**2 + yvals**2)

pathfile = "m14cut_hosts_1000.csv"
wpathfile = "w_m14cut_hosts_1000.csv"
prefix=""
hostfile = "craco_assigned_galaxies.csv"
zdmfile = "craco_900_mc_sample.csv"
CandDir = "CandidateFiles/"
image_size = 4.*10**2
main(prefix,pathfile,wpathfile,hostfile,zdmfile,CandDir,image_size)

hostfile = "loc30_craco_assigned_galaxies.csv"
pathfile = "loc30_m14cut_hosts_1000.csv"
wpathfile = "loc30_w_m14cut_hosts_1000.csv"
zdmfile = "craco_900_mc_sample.csv"
CandDir = "loc30CandidateFiles/"
prefix="loc30"
image_size = 4.*120**2 # 2 arcsec radius
main(prefix,pathfile,wpathfile,hostfile,zdmfile,CandDir,image_size,PlotCorrected=True)
