name: CI Tests

on:
  push:
    branches:
    - main
  pull_request:

env:
  SETUP_XVFB: True  # avoid issues if mpl tries to open a GUI window

jobs:
  ci-tests:
    name: Tox env ${{ matrix.python }}-${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8, 3.9]
        toxenv: [test, test-alldeps, test-astropydev]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Install zdm requirements 
      run: |
        python -m pip install wheel scipy IPython astropy extension-helpers mpmath
        python -m pip install git+https://github.com/FRBs/ne2001.git#egg=ne2001
        python -m pip install git+https://github.com/FRBs/FRB.git#egg=frb
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
